#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kimlik.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kimlik")]
	public partial class KimlikDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKisiBilgileri(KisiBilgileri instance);
    partial void UpdateKisiBilgileri(KisiBilgileri instance);
    partial void DeleteKisiBilgileri(KisiBilgileri instance);
    partial void InsertMusteriOnayKimlikTasarim(MusteriOnayKimlikTasarim instance);
    partial void UpdateMusteriOnayKimlikTasarim(MusteriOnayKimlikTasarim instance);
    partial void DeleteMusteriOnayKimlikTasarim(MusteriOnayKimlikTasarim instance);
    partial void InsertMusteri(Musteri instance);
    partial void UpdateMusteri(Musteri instance);
    partial void DeleteMusteri(Musteri instance);
    partial void InsertMusteriOnay(MusteriOnay instance);
    partial void UpdateMusteriOnay(MusteriOnay instance);
    partial void DeleteMusteriOnay(MusteriOnay instance);
    partial void InsertKmlikTasarim(KmlikTasarim instance);
    partial void UpdateKmlikTasarim(KmlikTasarim instance);
    partial void DeleteKmlikTasarim(KmlikTasarim instance);
    #endregion
		
		public KimlikDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["kimlikConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KimlikDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KimlikDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KimlikDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KimlikDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KisiBilgileri> KisiBilgileris
		{
			get
			{
				return this.GetTable<KisiBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<MusteriOnayKimlikTasarim> MusteriOnayKimlikTasarims
		{
			get
			{
				return this.GetTable<MusteriOnayKimlikTasarim>();
			}
		}
		
		public System.Data.Linq.Table<Musteri> Musteris
		{
			get
			{
				return this.GetTable<Musteri>();
			}
		}
		
		public System.Data.Linq.Table<MusteriOnay> MusteriOnays
		{
			get
			{
				return this.GetTable<MusteriOnay>();
			}
		}
		
		public System.Data.Linq.Table<KmlikTasarim> KmlikTasarims
		{
			get
			{
				return this.GetTable<KmlikTasarim>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KisiBilgileri")]
	public partial class KisiBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _MusteriOnayId;
		
		private System.Nullable<int> _KimlikTasarimId;
		
		private string _TCNo;
		
		private string _Soyadi;
		
		private string _Adi;
		
		private string _BabaAdi;
		
		private string _AnaAdi;
		
		private string _DogumYeri;
		
		private string _DogumTarih;
		
		private string _MedeniHali;
		
		private string _Din;
		
		private string _Il;
		
		private string _Ilce;
		
		private string _Mahalle;
		
		private string _CiltNo;
		
		private string _AileSiraNo;
		
		private string _SiraNo;
		
		private string _VerildigiYer;
		
		private string _VerilisNedeni;
		
		private string _KanGrubu;
		
		private string _KayitNo;
		
		private string _VerilisTarihi;
		
		private string _ImagePath;
		
		private EntityRef<MusteriOnay> _MusteriOnay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMusteriOnayIdChanging(System.Nullable<int> value);
    partial void OnMusteriOnayIdChanged();
    partial void OnKimlikTasarimIdChanging(System.Nullable<int> value);
    partial void OnKimlikTasarimIdChanged();
    partial void OnTCNoChanging(string value);
    partial void OnTCNoChanged();
    partial void OnSoyadiChanging(string value);
    partial void OnSoyadiChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnBabaAdiChanging(string value);
    partial void OnBabaAdiChanged();
    partial void OnAnaAdiChanging(string value);
    partial void OnAnaAdiChanged();
    partial void OnDogumYeriChanging(string value);
    partial void OnDogumYeriChanged();
    partial void OnDogumTarihChanging(string value);
    partial void OnDogumTarihChanged();
    partial void OnMedeniHaliChanging(string value);
    partial void OnMedeniHaliChanged();
    partial void OnDinChanging(string value);
    partial void OnDinChanged();
    partial void OnIlChanging(string value);
    partial void OnIlChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnMahalleChanging(string value);
    partial void OnMahalleChanged();
    partial void OnCiltNoChanging(string value);
    partial void OnCiltNoChanged();
    partial void OnAileSiraNoChanging(string value);
    partial void OnAileSiraNoChanged();
    partial void OnSiraNoChanging(string value);
    partial void OnSiraNoChanged();
    partial void OnVerildigiYerChanging(string value);
    partial void OnVerildigiYerChanged();
    partial void OnVerilisNedeniChanging(string value);
    partial void OnVerilisNedeniChanged();
    partial void OnKanGrubuChanging(string value);
    partial void OnKanGrubuChanged();
    partial void OnKayitNoChanging(string value);
    partial void OnKayitNoChanged();
    partial void OnVerilisTarihiChanging(string value);
    partial void OnVerilisTarihiChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    #endregion
		
		public KisiBilgileri()
		{
			this._MusteriOnay = default(EntityRef<MusteriOnay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriOnayId", DbType="Int")]
		public System.Nullable<int> MusteriOnayId
		{
			get
			{
				return this._MusteriOnayId;
			}
			set
			{
				if ((this._MusteriOnayId != value))
				{
					if (this._MusteriOnay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriOnayIdChanging(value);
					this.SendPropertyChanging();
					this._MusteriOnayId = value;
					this.SendPropertyChanged("MusteriOnayId");
					this.OnMusteriOnayIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikTasarimId", DbType="Int")]
		public System.Nullable<int> KimlikTasarimId
		{
			get
			{
				return this._KimlikTasarimId;
			}
			set
			{
				if ((this._KimlikTasarimId != value))
				{
					this.OnKimlikTasarimIdChanging(value);
					this.SendPropertyChanging();
					this._KimlikTasarimId = value;
					this.SendPropertyChanged("KimlikTasarimId");
					this.OnKimlikTasarimIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCNo", DbType="NVarChar(MAX)")]
		public string TCNo
		{
			get
			{
				return this._TCNo;
			}
			set
			{
				if ((this._TCNo != value))
				{
					this.OnTCNoChanging(value);
					this.SendPropertyChanging();
					this._TCNo = value;
					this.SendPropertyChanged("TCNo");
					this.OnTCNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NVarChar(MAX)")]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this.OnSoyadiChanging(value);
					this.SendPropertyChanging();
					this._Soyadi = value;
					this.SendPropertyChanged("Soyadi");
					this.OnSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(MAX)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BabaAdi", DbType="NVarChar(MAX)")]
		public string BabaAdi
		{
			get
			{
				return this._BabaAdi;
			}
			set
			{
				if ((this._BabaAdi != value))
				{
					this.OnBabaAdiChanging(value);
					this.SendPropertyChanging();
					this._BabaAdi = value;
					this.SendPropertyChanged("BabaAdi");
					this.OnBabaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnaAdi", DbType="NVarChar(MAX)")]
		public string AnaAdi
		{
			get
			{
				return this._AnaAdi;
			}
			set
			{
				if ((this._AnaAdi != value))
				{
					this.OnAnaAdiChanging(value);
					this.SendPropertyChanging();
					this._AnaAdi = value;
					this.SendPropertyChanged("AnaAdi");
					this.OnAnaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumYeri", DbType="NVarChar(MAX)")]
		public string DogumYeri
		{
			get
			{
				return this._DogumYeri;
			}
			set
			{
				if ((this._DogumYeri != value))
				{
					this.OnDogumYeriChanging(value);
					this.SendPropertyChanging();
					this._DogumYeri = value;
					this.SendPropertyChanged("DogumYeri");
					this.OnDogumYeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarih", DbType="NVarChar(MAX)")]
		public string DogumTarih
		{
			get
			{
				return this._DogumTarih;
			}
			set
			{
				if ((this._DogumTarih != value))
				{
					this.OnDogumTarihChanging(value);
					this.SendPropertyChanging();
					this._DogumTarih = value;
					this.SendPropertyChanged("DogumTarih");
					this.OnDogumTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedeniHali", DbType="NVarChar(50)")]
		public string MedeniHali
		{
			get
			{
				return this._MedeniHali;
			}
			set
			{
				if ((this._MedeniHali != value))
				{
					this.OnMedeniHaliChanging(value);
					this.SendPropertyChanging();
					this._MedeniHali = value;
					this.SendPropertyChanged("MedeniHali");
					this.OnMedeniHaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Din", DbType="NVarChar(50)")]
		public string Din
		{
			get
			{
				return this._Din;
			}
			set
			{
				if ((this._Din != value))
				{
					this.OnDinChanging(value);
					this.SendPropertyChanging();
					this._Din = value;
					this.SendPropertyChanged("Din");
					this.OnDinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(50)")]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this.OnIlChanging(value);
					this.SendPropertyChanging();
					this._Il = value;
					this.SendPropertyChanged("Il");
					this.OnIlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahalle", DbType="NVarChar(MAX)")]
		public string Mahalle
		{
			get
			{
				return this._Mahalle;
			}
			set
			{
				if ((this._Mahalle != value))
				{
					this.OnMahalleChanging(value);
					this.SendPropertyChanging();
					this._Mahalle = value;
					this.SendPropertyChanged("Mahalle");
					this.OnMahalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiltNo", DbType="NVarChar(50)")]
		public string CiltNo
		{
			get
			{
				return this._CiltNo;
			}
			set
			{
				if ((this._CiltNo != value))
				{
					this.OnCiltNoChanging(value);
					this.SendPropertyChanging();
					this._CiltNo = value;
					this.SendPropertyChanged("CiltNo");
					this.OnCiltNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AileSiraNo", DbType="NVarChar(50)")]
		public string AileSiraNo
		{
			get
			{
				return this._AileSiraNo;
			}
			set
			{
				if ((this._AileSiraNo != value))
				{
					this.OnAileSiraNoChanging(value);
					this.SendPropertyChanging();
					this._AileSiraNo = value;
					this.SendPropertyChanged("AileSiraNo");
					this.OnAileSiraNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiraNo", DbType="NVarChar(50)")]
		public string SiraNo
		{
			get
			{
				return this._SiraNo;
			}
			set
			{
				if ((this._SiraNo != value))
				{
					this.OnSiraNoChanging(value);
					this.SendPropertyChanging();
					this._SiraNo = value;
					this.SendPropertyChanged("SiraNo");
					this.OnSiraNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerildigiYer", DbType="NVarChar(100)")]
		public string VerildigiYer
		{
			get
			{
				return this._VerildigiYer;
			}
			set
			{
				if ((this._VerildigiYer != value))
				{
					this.OnVerildigiYerChanging(value);
					this.SendPropertyChanging();
					this._VerildigiYer = value;
					this.SendPropertyChanged("VerildigiYer");
					this.OnVerildigiYerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerilisNedeni", DbType="NVarChar(100)")]
		public string VerilisNedeni
		{
			get
			{
				return this._VerilisNedeni;
			}
			set
			{
				if ((this._VerilisNedeni != value))
				{
					this.OnVerilisNedeniChanging(value);
					this.SendPropertyChanging();
					this._VerilisNedeni = value;
					this.SendPropertyChanged("VerilisNedeni");
					this.OnVerilisNedeniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KanGrubu", DbType="NVarChar(50)")]
		public string KanGrubu
		{
			get
			{
				return this._KanGrubu;
			}
			set
			{
				if ((this._KanGrubu != value))
				{
					this.OnKanGrubuChanging(value);
					this.SendPropertyChanging();
					this._KanGrubu = value;
					this.SendPropertyChanged("KanGrubu");
					this.OnKanGrubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KayitNo", DbType="NVarChar(50)")]
		public string KayitNo
		{
			get
			{
				return this._KayitNo;
			}
			set
			{
				if ((this._KayitNo != value))
				{
					this.OnKayitNoChanging(value);
					this.SendPropertyChanging();
					this._KayitNo = value;
					this.SendPropertyChanged("KayitNo");
					this.OnKayitNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerilisTarihi", DbType="NVarChar(50)")]
		public string VerilisTarihi
		{
			get
			{
				return this._VerilisTarihi;
			}
			set
			{
				if ((this._VerilisTarihi != value))
				{
					this.OnVerilisTarihiChanging(value);
					this.SendPropertyChanging();
					this._VerilisTarihi = value;
					this.SendPropertyChanged("VerilisTarihi");
					this.OnVerilisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="NVarChar(MAX)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MusteriOnay_KisiBilgileri", Storage="_MusteriOnay", ThisKey="MusteriOnayId", OtherKey="Id", IsForeignKey=true)]
		public MusteriOnay MusteriOnay
		{
			get
			{
				return this._MusteriOnay.Entity;
			}
			set
			{
				MusteriOnay previousValue = this._MusteriOnay.Entity;
				if (((previousValue != value) 
							|| (this._MusteriOnay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MusteriOnay.Entity = null;
						previousValue.KisiBilgileris.Remove(this);
					}
					this._MusteriOnay.Entity = value;
					if ((value != null))
					{
						value.KisiBilgileris.Add(this);
						this._MusteriOnayId = value.Id;
					}
					else
					{
						this._MusteriOnayId = default(Nullable<int>);
					}
					this.SendPropertyChanged("MusteriOnay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusteriOnayKimlikTasarim")]
	public partial class MusteriOnayKimlikTasarim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MusteriOnayId;
		
		private int _KimlikTasarimId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMusteriOnayIdChanging(int value);
    partial void OnMusteriOnayIdChanged();
    partial void OnKimlikTasarimIdChanging(int value);
    partial void OnKimlikTasarimIdChanged();
    #endregion
		
		public MusteriOnayKimlikTasarim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriOnayId", DbType="Int NOT NULL")]
		public int MusteriOnayId
		{
			get
			{
				return this._MusteriOnayId;
			}
			set
			{
				if ((this._MusteriOnayId != value))
				{
					this.OnMusteriOnayIdChanging(value);
					this.SendPropertyChanging();
					this._MusteriOnayId = value;
					this.SendPropertyChanged("MusteriOnayId");
					this.OnMusteriOnayIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikTasarimId", DbType="Int NOT NULL")]
		public int KimlikTasarimId
		{
			get
			{
				return this._KimlikTasarimId;
			}
			set
			{
				if ((this._KimlikTasarimId != value))
				{
					this.OnKimlikTasarimIdChanging(value);
					this.SendPropertyChanging();
					this._KimlikTasarimId = value;
					this.SendPropertyChanged("KimlikTasarimId");
					this.OnKimlikTasarimIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteri")]
	public partial class Musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _SirketAdi;
		
		private string _AdiSoyadi;
		
		private string _Telefon;
		
		private string _EmailAddress;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<bool> _IsReaded;
		
		private System.Nullable<bool> _IsSpecialDesign;
		
		private EntitySet<MusteriOnay> _MusteriOnays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSirketAdiChanging(string value);
    partial void OnSirketAdiChanged();
    partial void OnAdiSoyadiChanging(string value);
    partial void OnAdiSoyadiChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnIsReadedChanging(System.Nullable<bool> value);
    partial void OnIsReadedChanged();
    partial void OnIsSpecialDesignChanging(System.Nullable<bool> value);
    partial void OnIsSpecialDesignChanged();
    #endregion
		
		public Musteri()
		{
			this._MusteriOnays = new EntitySet<MusteriOnay>(new Action<MusteriOnay>(this.attach_MusteriOnays), new Action<MusteriOnay>(this.detach_MusteriOnays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SirketAdi", DbType="NVarChar(MAX)")]
		public string SirketAdi
		{
			get
			{
				return this._SirketAdi;
			}
			set
			{
				if ((this._SirketAdi != value))
				{
					this.OnSirketAdiChanging(value);
					this.SendPropertyChanging();
					this._SirketAdi = value;
					this.SendPropertyChanged("SirketAdi");
					this.OnSirketAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdiSoyadi", DbType="NVarChar(MAX)")]
		public string AdiSoyadi
		{
			get
			{
				return this._AdiSoyadi;
			}
			set
			{
				if ((this._AdiSoyadi != value))
				{
					this.OnAdiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._AdiSoyadi = value;
					this.SendPropertyChanged("AdiSoyadi");
					this.OnAdiSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(MAX)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(MAX)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReaded", DbType="Bit")]
		public System.Nullable<bool> IsReaded
		{
			get
			{
				return this._IsReaded;
			}
			set
			{
				if ((this._IsReaded != value))
				{
					this.OnIsReadedChanging(value);
					this.SendPropertyChanging();
					this._IsReaded = value;
					this.SendPropertyChanged("IsReaded");
					this.OnIsReadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSpecialDesign", DbType="Bit")]
		public System.Nullable<bool> IsSpecialDesign
		{
			get
			{
				return this._IsSpecialDesign;
			}
			set
			{
				if ((this._IsSpecialDesign != value))
				{
					this.OnIsSpecialDesignChanging(value);
					this.SendPropertyChanging();
					this._IsSpecialDesign = value;
					this.SendPropertyChanged("IsSpecialDesign");
					this.OnIsSpecialDesignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteri_MusteriOnay", Storage="_MusteriOnays", ThisKey="Id", OtherKey="MusteriId")]
		public EntitySet<MusteriOnay> MusteriOnays
		{
			get
			{
				return this._MusteriOnays;
			}
			set
			{
				this._MusteriOnays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MusteriOnays(MusteriOnay entity)
		{
			this.SendPropertyChanging();
			entity.Musteri = this;
		}
		
		private void detach_MusteriOnays(MusteriOnay entity)
		{
			this.SendPropertyChanging();
			entity.Musteri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusteriOnay")]
	public partial class MusteriOnay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _MusteriId;
		
		private string _UserName;
		
		private string _Pass;
		
		private System.Nullable<bool> _IsConfirm;
		
		private string _CardDesignFilePath;
		
		private EntitySet<KisiBilgileri> _KisiBilgileris;
		
		private EntityRef<Musteri> _Musteri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMusteriIdChanging(int value);
    partial void OnMusteriIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnIsConfirmChanging(System.Nullable<bool> value);
    partial void OnIsConfirmChanged();
    partial void OnCardDesignFilePathChanging(string value);
    partial void OnCardDesignFilePathChanged();
    #endregion
		
		public MusteriOnay()
		{
			this._KisiBilgileris = new EntitySet<KisiBilgileri>(new Action<KisiBilgileri>(this.attach_KisiBilgileris), new Action<KisiBilgileri>(this.detach_KisiBilgileris));
			this._Musteri = default(EntityRef<Musteri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriId", DbType="Int NOT NULL")]
		public int MusteriId
		{
			get
			{
				return this._MusteriId;
			}
			set
			{
				if ((this._MusteriId != value))
				{
					if (this._Musteri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriIdChanging(value);
					this.SendPropertyChanging();
					this._MusteriId = value;
					this.SendPropertyChanged("MusteriId");
					this.OnMusteriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(MAX)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsConfirm", DbType="Bit")]
		public System.Nullable<bool> IsConfirm
		{
			get
			{
				return this._IsConfirm;
			}
			set
			{
				if ((this._IsConfirm != value))
				{
					this.OnIsConfirmChanging(value);
					this.SendPropertyChanging();
					this._IsConfirm = value;
					this.SendPropertyChanged("IsConfirm");
					this.OnIsConfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardDesignFilePath", DbType="NVarChar(MAX)")]
		public string CardDesignFilePath
		{
			get
			{
				return this._CardDesignFilePath;
			}
			set
			{
				if ((this._CardDesignFilePath != value))
				{
					this.OnCardDesignFilePathChanging(value);
					this.SendPropertyChanging();
					this._CardDesignFilePath = value;
					this.SendPropertyChanged("CardDesignFilePath");
					this.OnCardDesignFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MusteriOnay_KisiBilgileri", Storage="_KisiBilgileris", ThisKey="Id", OtherKey="MusteriOnayId")]
		public EntitySet<KisiBilgileri> KisiBilgileris
		{
			get
			{
				return this._KisiBilgileris;
			}
			set
			{
				this._KisiBilgileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteri_MusteriOnay", Storage="_Musteri", ThisKey="MusteriId", OtherKey="Id", IsForeignKey=true)]
		public Musteri Musteri
		{
			get
			{
				return this._Musteri.Entity;
			}
			set
			{
				Musteri previousValue = this._Musteri.Entity;
				if (((previousValue != value) 
							|| (this._Musteri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteri.Entity = null;
						previousValue.MusteriOnays.Remove(this);
					}
					this._Musteri.Entity = value;
					if ((value != null))
					{
						value.MusteriOnays.Add(this);
						this._MusteriId = value.Id;
					}
					else
					{
						this._MusteriId = default(int);
					}
					this.SendPropertyChanged("Musteri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KisiBilgileris(KisiBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.MusteriOnay = this;
		}
		
		private void detach_KisiBilgileris(KisiBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.MusteriOnay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KmlikTasarim")]
	public partial class KmlikTasarim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KimlikAdi;
		
		private string _Color;
		
		private string _ColorPano;
		
		private string _ColorFont;
		
		private string _ColorFont2;
		
		private string _ColorFont3;
		
		private string _KimlikBaslik;
		
		private string _KimlikAltBaslik;
		
		private string _KimlikOnAraBaslik;
		
		private string _ImageLeft;
		
		private string _ImageRight;
		
		private string _Etiket1;
		
		private string _Etiket1Eng;
		
		private string _Etiket2;
		
		private string _Etiket2Eng;
		
		private string _Etiket3;
		
		private string _Etiket3Eng;
		
		private string _Etiket4;
		
		private string _Etiket4Eng;
		
		private string _Etiket5;
		
		private string _Etiket5Eng;
		
		private string _Etiket6;
		
		private string _Etiket6Eng;
		
		private string _Etiket7;
		
		private string _Etiket7Eng;
		
		private string _KimlikBaslikArka;
		
		private string _KimlikBaslikArkaEng;
		
		private string _etiketArkaOrtaBaslik;
		
		private string _etiketArkaOrtaBaslikEng;
		
		private string _Etiket1Arka;
		
		private string _Etiket1ArkaEng;
		
		private string _Etiket2Arka;
		
		private string _Etiket2ArkaEng;
		
		private string _Etiket3Arka;
		
		private string _Etiket3ArkaEng;
		
		private string _Etiket4Arka;
		
		private string _Etiket4ArkaEng;
		
		private string _Etiket5Arka;
		
		private string _Etiket5ArkaEng;
		
		private string _Etiket6Arka;
		
		private string _Etiket6ArkaEng;
		
		private string _Etiket7Arka;
		
		private string _Etiket7ArkaEng;
		
		private string _Etiket8Arka;
		
		private string _Etiket8ArkaEng;
		
		private string _Etiket9Arka;
		
		private string _Etiket9ArkaEng;
		
		private string _Etiket10Arka;
		
		private string _Etiket10ArkaEng;
		
		private string _Etiket11Arka;
		
		private string _Etiket11ArkaEng;
		
		private string _Etiket12Arka;
		
		private string _Etiket12ArkaEng;
		
		private string _Etiket13Arka;
		
		private string _Etiket13ArkaEng;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKimlikAdiChanging(string value);
    partial void OnKimlikAdiChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnColorPanoChanging(string value);
    partial void OnColorPanoChanged();
    partial void OnColorFontChanging(string value);
    partial void OnColorFontChanged();
    partial void OnColorFont2Changing(string value);
    partial void OnColorFont2Changed();
    partial void OnColorFont3Changing(string value);
    partial void OnColorFont3Changed();
    partial void OnKimlikBaslikChanging(string value);
    partial void OnKimlikBaslikChanged();
    partial void OnKimlikAltBaslikChanging(string value);
    partial void OnKimlikAltBaslikChanged();
    partial void OnKimlikOnAraBaslikChanging(string value);
    partial void OnKimlikOnAraBaslikChanged();
    partial void OnImageLeftChanging(string value);
    partial void OnImageLeftChanged();
    partial void OnImageRightChanging(string value);
    partial void OnImageRightChanged();
    partial void OnEtiket1Changing(string value);
    partial void OnEtiket1Changed();
    partial void OnEtiket1EngChanging(string value);
    partial void OnEtiket1EngChanged();
    partial void OnEtiket2Changing(string value);
    partial void OnEtiket2Changed();
    partial void OnEtiket2EngChanging(string value);
    partial void OnEtiket2EngChanged();
    partial void OnEtiket3Changing(string value);
    partial void OnEtiket3Changed();
    partial void OnEtiket3EngChanging(string value);
    partial void OnEtiket3EngChanged();
    partial void OnEtiket4Changing(string value);
    partial void OnEtiket4Changed();
    partial void OnEtiket4EngChanging(string value);
    partial void OnEtiket4EngChanged();
    partial void OnEtiket5Changing(string value);
    partial void OnEtiket5Changed();
    partial void OnEtiket5EngChanging(string value);
    partial void OnEtiket5EngChanged();
    partial void OnEtiket6Changing(string value);
    partial void OnEtiket6Changed();
    partial void OnEtiket6EngChanging(string value);
    partial void OnEtiket6EngChanged();
    partial void OnEtiket7Changing(string value);
    partial void OnEtiket7Changed();
    partial void OnEtiket7EngChanging(string value);
    partial void OnEtiket7EngChanged();
    partial void OnKimlikBaslikArkaChanging(string value);
    partial void OnKimlikBaslikArkaChanged();
    partial void OnKimlikBaslikArkaEngChanging(string value);
    partial void OnKimlikBaslikArkaEngChanged();
    partial void OnetiketArkaOrtaBaslikChanging(string value);
    partial void OnetiketArkaOrtaBaslikChanged();
    partial void OnetiketArkaOrtaBaslikEngChanging(string value);
    partial void OnetiketArkaOrtaBaslikEngChanged();
    partial void OnEtiket1ArkaChanging(string value);
    partial void OnEtiket1ArkaChanged();
    partial void OnEtiket1ArkaEngChanging(string value);
    partial void OnEtiket1ArkaEngChanged();
    partial void OnEtiket2ArkaChanging(string value);
    partial void OnEtiket2ArkaChanged();
    partial void OnEtiket2ArkaEngChanging(string value);
    partial void OnEtiket2ArkaEngChanged();
    partial void OnEtiket3ArkaChanging(string value);
    partial void OnEtiket3ArkaChanged();
    partial void OnEtiket3ArkaEngChanging(string value);
    partial void OnEtiket3ArkaEngChanged();
    partial void OnEtiket4ArkaChanging(string value);
    partial void OnEtiket4ArkaChanged();
    partial void OnEtiket4ArkaEngChanging(string value);
    partial void OnEtiket4ArkaEngChanged();
    partial void OnEtiket5ArkaChanging(string value);
    partial void OnEtiket5ArkaChanged();
    partial void OnEtiket5ArkaEngChanging(string value);
    partial void OnEtiket5ArkaEngChanged();
    partial void OnEtiket6ArkaChanging(string value);
    partial void OnEtiket6ArkaChanged();
    partial void OnEtiket6ArkaEngChanging(string value);
    partial void OnEtiket6ArkaEngChanged();
    partial void OnEtiket7ArkaChanging(string value);
    partial void OnEtiket7ArkaChanged();
    partial void OnEtiket7ArkaEngChanging(string value);
    partial void OnEtiket7ArkaEngChanged();
    partial void OnEtiket8ArkaChanging(string value);
    partial void OnEtiket8ArkaChanged();
    partial void OnEtiket8ArkaEngChanging(string value);
    partial void OnEtiket8ArkaEngChanged();
    partial void OnEtiket9ArkaChanging(string value);
    partial void OnEtiket9ArkaChanged();
    partial void OnEtiket9ArkaEngChanging(string value);
    partial void OnEtiket9ArkaEngChanged();
    partial void OnEtiket10ArkaChanging(string value);
    partial void OnEtiket10ArkaChanged();
    partial void OnEtiket10ArkaEngChanging(string value);
    partial void OnEtiket10ArkaEngChanged();
    partial void OnEtiket11ArkaChanging(string value);
    partial void OnEtiket11ArkaChanged();
    partial void OnEtiket11ArkaEngChanging(string value);
    partial void OnEtiket11ArkaEngChanged();
    partial void OnEtiket12ArkaChanging(string value);
    partial void OnEtiket12ArkaChanged();
    partial void OnEtiket12ArkaEngChanging(string value);
    partial void OnEtiket12ArkaEngChanged();
    partial void OnEtiket13ArkaChanging(string value);
    partial void OnEtiket13ArkaChanged();
    partial void OnEtiket13ArkaEngChanging(string value);
    partial void OnEtiket13ArkaEngChanged();
    #endregion
		
		public KmlikTasarim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikAdi", DbType="NVarChar(MAX)")]
		public string KimlikAdi
		{
			get
			{
				return this._KimlikAdi;
			}
			set
			{
				if ((this._KimlikAdi != value))
				{
					this.OnKimlikAdiChanging(value);
					this.SendPropertyChanging();
					this._KimlikAdi = value;
					this.SendPropertyChanged("KimlikAdi");
					this.OnKimlikAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorPano", DbType="NVarChar(50)")]
		public string ColorPano
		{
			get
			{
				return this._ColorPano;
			}
			set
			{
				if ((this._ColorPano != value))
				{
					this.OnColorPanoChanging(value);
					this.SendPropertyChanging();
					this._ColorPano = value;
					this.SendPropertyChanged("ColorPano");
					this.OnColorPanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorFont", DbType="NVarChar(MAX)")]
		public string ColorFont
		{
			get
			{
				return this._ColorFont;
			}
			set
			{
				if ((this._ColorFont != value))
				{
					this.OnColorFontChanging(value);
					this.SendPropertyChanging();
					this._ColorFont = value;
					this.SendPropertyChanged("ColorFont");
					this.OnColorFontChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorFont2", DbType="NVarChar(MAX)")]
		public string ColorFont2
		{
			get
			{
				return this._ColorFont2;
			}
			set
			{
				if ((this._ColorFont2 != value))
				{
					this.OnColorFont2Changing(value);
					this.SendPropertyChanging();
					this._ColorFont2 = value;
					this.SendPropertyChanged("ColorFont2");
					this.OnColorFont2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorFont3", DbType="NVarChar(MAX)")]
		public string ColorFont3
		{
			get
			{
				return this._ColorFont3;
			}
			set
			{
				if ((this._ColorFont3 != value))
				{
					this.OnColorFont3Changing(value);
					this.SendPropertyChanging();
					this._ColorFont3 = value;
					this.SendPropertyChanged("ColorFont3");
					this.OnColorFont3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikBaslik", DbType="NVarChar(MAX)")]
		public string KimlikBaslik
		{
			get
			{
				return this._KimlikBaslik;
			}
			set
			{
				if ((this._KimlikBaslik != value))
				{
					this.OnKimlikBaslikChanging(value);
					this.SendPropertyChanging();
					this._KimlikBaslik = value;
					this.SendPropertyChanged("KimlikBaslik");
					this.OnKimlikBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikAltBaslik", DbType="NVarChar(MAX)")]
		public string KimlikAltBaslik
		{
			get
			{
				return this._KimlikAltBaslik;
			}
			set
			{
				if ((this._KimlikAltBaslik != value))
				{
					this.OnKimlikAltBaslikChanging(value);
					this.SendPropertyChanging();
					this._KimlikAltBaslik = value;
					this.SendPropertyChanged("KimlikAltBaslik");
					this.OnKimlikAltBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikOnAraBaslik", DbType="NVarChar(MAX)")]
		public string KimlikOnAraBaslik
		{
			get
			{
				return this._KimlikOnAraBaslik;
			}
			set
			{
				if ((this._KimlikOnAraBaslik != value))
				{
					this.OnKimlikOnAraBaslikChanging(value);
					this.SendPropertyChanging();
					this._KimlikOnAraBaslik = value;
					this.SendPropertyChanged("KimlikOnAraBaslik");
					this.OnKimlikOnAraBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageLeft", DbType="NVarChar(MAX)")]
		public string ImageLeft
		{
			get
			{
				return this._ImageLeft;
			}
			set
			{
				if ((this._ImageLeft != value))
				{
					this.OnImageLeftChanging(value);
					this.SendPropertyChanging();
					this._ImageLeft = value;
					this.SendPropertyChanged("ImageLeft");
					this.OnImageLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageRight", DbType="NVarChar(MAX)")]
		public string ImageRight
		{
			get
			{
				return this._ImageRight;
			}
			set
			{
				if ((this._ImageRight != value))
				{
					this.OnImageRightChanging(value);
					this.SendPropertyChanging();
					this._ImageRight = value;
					this.SendPropertyChanged("ImageRight");
					this.OnImageRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket1", DbType="NVarChar(MAX)")]
		public string Etiket1
		{
			get
			{
				return this._Etiket1;
			}
			set
			{
				if ((this._Etiket1 != value))
				{
					this.OnEtiket1Changing(value);
					this.SendPropertyChanging();
					this._Etiket1 = value;
					this.SendPropertyChanged("Etiket1");
					this.OnEtiket1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket1Eng", DbType="NVarChar(MAX)")]
		public string Etiket1Eng
		{
			get
			{
				return this._Etiket1Eng;
			}
			set
			{
				if ((this._Etiket1Eng != value))
				{
					this.OnEtiket1EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket1Eng = value;
					this.SendPropertyChanged("Etiket1Eng");
					this.OnEtiket1EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket2", DbType="NVarChar(MAX)")]
		public string Etiket2
		{
			get
			{
				return this._Etiket2;
			}
			set
			{
				if ((this._Etiket2 != value))
				{
					this.OnEtiket2Changing(value);
					this.SendPropertyChanging();
					this._Etiket2 = value;
					this.SendPropertyChanged("Etiket2");
					this.OnEtiket2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket2Eng", DbType="NVarChar(MAX)")]
		public string Etiket2Eng
		{
			get
			{
				return this._Etiket2Eng;
			}
			set
			{
				if ((this._Etiket2Eng != value))
				{
					this.OnEtiket2EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket2Eng = value;
					this.SendPropertyChanged("Etiket2Eng");
					this.OnEtiket2EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket3", DbType="NVarChar(MAX)")]
		public string Etiket3
		{
			get
			{
				return this._Etiket3;
			}
			set
			{
				if ((this._Etiket3 != value))
				{
					this.OnEtiket3Changing(value);
					this.SendPropertyChanging();
					this._Etiket3 = value;
					this.SendPropertyChanged("Etiket3");
					this.OnEtiket3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket3Eng", DbType="NVarChar(MAX)")]
		public string Etiket3Eng
		{
			get
			{
				return this._Etiket3Eng;
			}
			set
			{
				if ((this._Etiket3Eng != value))
				{
					this.OnEtiket3EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket3Eng = value;
					this.SendPropertyChanged("Etiket3Eng");
					this.OnEtiket3EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket4", DbType="NVarChar(MAX)")]
		public string Etiket4
		{
			get
			{
				return this._Etiket4;
			}
			set
			{
				if ((this._Etiket4 != value))
				{
					this.OnEtiket4Changing(value);
					this.SendPropertyChanging();
					this._Etiket4 = value;
					this.SendPropertyChanged("Etiket4");
					this.OnEtiket4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket4Eng", DbType="NVarChar(MAX)")]
		public string Etiket4Eng
		{
			get
			{
				return this._Etiket4Eng;
			}
			set
			{
				if ((this._Etiket4Eng != value))
				{
					this.OnEtiket4EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket4Eng = value;
					this.SendPropertyChanged("Etiket4Eng");
					this.OnEtiket4EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket5", DbType="NVarChar(MAX)")]
		public string Etiket5
		{
			get
			{
				return this._Etiket5;
			}
			set
			{
				if ((this._Etiket5 != value))
				{
					this.OnEtiket5Changing(value);
					this.SendPropertyChanging();
					this._Etiket5 = value;
					this.SendPropertyChanged("Etiket5");
					this.OnEtiket5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket5Eng", DbType="NVarChar(MAX)")]
		public string Etiket5Eng
		{
			get
			{
				return this._Etiket5Eng;
			}
			set
			{
				if ((this._Etiket5Eng != value))
				{
					this.OnEtiket5EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket5Eng = value;
					this.SendPropertyChanged("Etiket5Eng");
					this.OnEtiket5EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket6", DbType="NVarChar(MAX)")]
		public string Etiket6
		{
			get
			{
				return this._Etiket6;
			}
			set
			{
				if ((this._Etiket6 != value))
				{
					this.OnEtiket6Changing(value);
					this.SendPropertyChanging();
					this._Etiket6 = value;
					this.SendPropertyChanged("Etiket6");
					this.OnEtiket6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket6Eng", DbType="NVarChar(MAX)")]
		public string Etiket6Eng
		{
			get
			{
				return this._Etiket6Eng;
			}
			set
			{
				if ((this._Etiket6Eng != value))
				{
					this.OnEtiket6EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket6Eng = value;
					this.SendPropertyChanged("Etiket6Eng");
					this.OnEtiket6EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket7", DbType="NVarChar(MAX)")]
		public string Etiket7
		{
			get
			{
				return this._Etiket7;
			}
			set
			{
				if ((this._Etiket7 != value))
				{
					this.OnEtiket7Changing(value);
					this.SendPropertyChanging();
					this._Etiket7 = value;
					this.SendPropertyChanged("Etiket7");
					this.OnEtiket7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket7Eng", DbType="NVarChar(MAX)")]
		public string Etiket7Eng
		{
			get
			{
				return this._Etiket7Eng;
			}
			set
			{
				if ((this._Etiket7Eng != value))
				{
					this.OnEtiket7EngChanging(value);
					this.SendPropertyChanging();
					this._Etiket7Eng = value;
					this.SendPropertyChanged("Etiket7Eng");
					this.OnEtiket7EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikBaslikArka", DbType="NVarChar(MAX)")]
		public string KimlikBaslikArka
		{
			get
			{
				return this._KimlikBaslikArka;
			}
			set
			{
				if ((this._KimlikBaslikArka != value))
				{
					this.OnKimlikBaslikArkaChanging(value);
					this.SendPropertyChanging();
					this._KimlikBaslikArka = value;
					this.SendPropertyChanged("KimlikBaslikArka");
					this.OnKimlikBaslikArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikBaslikArkaEng", DbType="NVarChar(MAX)")]
		public string KimlikBaslikArkaEng
		{
			get
			{
				return this._KimlikBaslikArkaEng;
			}
			set
			{
				if ((this._KimlikBaslikArkaEng != value))
				{
					this.OnKimlikBaslikArkaEngChanging(value);
					this.SendPropertyChanging();
					this._KimlikBaslikArkaEng = value;
					this.SendPropertyChanged("KimlikBaslikArkaEng");
					this.OnKimlikBaslikArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etiketArkaOrtaBaslik", DbType="NVarChar(MAX)")]
		public string etiketArkaOrtaBaslik
		{
			get
			{
				return this._etiketArkaOrtaBaslik;
			}
			set
			{
				if ((this._etiketArkaOrtaBaslik != value))
				{
					this.OnetiketArkaOrtaBaslikChanging(value);
					this.SendPropertyChanging();
					this._etiketArkaOrtaBaslik = value;
					this.SendPropertyChanged("etiketArkaOrtaBaslik");
					this.OnetiketArkaOrtaBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etiketArkaOrtaBaslikEng", DbType="NVarChar(MAX)")]
		public string etiketArkaOrtaBaslikEng
		{
			get
			{
				return this._etiketArkaOrtaBaslikEng;
			}
			set
			{
				if ((this._etiketArkaOrtaBaslikEng != value))
				{
					this.OnetiketArkaOrtaBaslikEngChanging(value);
					this.SendPropertyChanging();
					this._etiketArkaOrtaBaslikEng = value;
					this.SendPropertyChanged("etiketArkaOrtaBaslikEng");
					this.OnetiketArkaOrtaBaslikEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket1Arka", DbType="NVarChar(MAX)")]
		public string Etiket1Arka
		{
			get
			{
				return this._Etiket1Arka;
			}
			set
			{
				if ((this._Etiket1Arka != value))
				{
					this.OnEtiket1ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket1Arka = value;
					this.SendPropertyChanged("Etiket1Arka");
					this.OnEtiket1ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket1ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket1ArkaEng
		{
			get
			{
				return this._Etiket1ArkaEng;
			}
			set
			{
				if ((this._Etiket1ArkaEng != value))
				{
					this.OnEtiket1ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket1ArkaEng = value;
					this.SendPropertyChanged("Etiket1ArkaEng");
					this.OnEtiket1ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket2Arka", DbType="NVarChar(MAX)")]
		public string Etiket2Arka
		{
			get
			{
				return this._Etiket2Arka;
			}
			set
			{
				if ((this._Etiket2Arka != value))
				{
					this.OnEtiket2ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket2Arka = value;
					this.SendPropertyChanged("Etiket2Arka");
					this.OnEtiket2ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket2ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket2ArkaEng
		{
			get
			{
				return this._Etiket2ArkaEng;
			}
			set
			{
				if ((this._Etiket2ArkaEng != value))
				{
					this.OnEtiket2ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket2ArkaEng = value;
					this.SendPropertyChanged("Etiket2ArkaEng");
					this.OnEtiket2ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket3Arka", DbType="NVarChar(MAX)")]
		public string Etiket3Arka
		{
			get
			{
				return this._Etiket3Arka;
			}
			set
			{
				if ((this._Etiket3Arka != value))
				{
					this.OnEtiket3ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket3Arka = value;
					this.SendPropertyChanged("Etiket3Arka");
					this.OnEtiket3ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket3ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket3ArkaEng
		{
			get
			{
				return this._Etiket3ArkaEng;
			}
			set
			{
				if ((this._Etiket3ArkaEng != value))
				{
					this.OnEtiket3ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket3ArkaEng = value;
					this.SendPropertyChanged("Etiket3ArkaEng");
					this.OnEtiket3ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket4Arka", DbType="NVarChar(MAX)")]
		public string Etiket4Arka
		{
			get
			{
				return this._Etiket4Arka;
			}
			set
			{
				if ((this._Etiket4Arka != value))
				{
					this.OnEtiket4ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket4Arka = value;
					this.SendPropertyChanged("Etiket4Arka");
					this.OnEtiket4ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket4ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket4ArkaEng
		{
			get
			{
				return this._Etiket4ArkaEng;
			}
			set
			{
				if ((this._Etiket4ArkaEng != value))
				{
					this.OnEtiket4ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket4ArkaEng = value;
					this.SendPropertyChanged("Etiket4ArkaEng");
					this.OnEtiket4ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket5Arka", DbType="NVarChar(MAX)")]
		public string Etiket5Arka
		{
			get
			{
				return this._Etiket5Arka;
			}
			set
			{
				if ((this._Etiket5Arka != value))
				{
					this.OnEtiket5ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket5Arka = value;
					this.SendPropertyChanged("Etiket5Arka");
					this.OnEtiket5ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket5ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket5ArkaEng
		{
			get
			{
				return this._Etiket5ArkaEng;
			}
			set
			{
				if ((this._Etiket5ArkaEng != value))
				{
					this.OnEtiket5ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket5ArkaEng = value;
					this.SendPropertyChanged("Etiket5ArkaEng");
					this.OnEtiket5ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket6Arka", DbType="NVarChar(MAX)")]
		public string Etiket6Arka
		{
			get
			{
				return this._Etiket6Arka;
			}
			set
			{
				if ((this._Etiket6Arka != value))
				{
					this.OnEtiket6ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket6Arka = value;
					this.SendPropertyChanged("Etiket6Arka");
					this.OnEtiket6ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket6ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket6ArkaEng
		{
			get
			{
				return this._Etiket6ArkaEng;
			}
			set
			{
				if ((this._Etiket6ArkaEng != value))
				{
					this.OnEtiket6ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket6ArkaEng = value;
					this.SendPropertyChanged("Etiket6ArkaEng");
					this.OnEtiket6ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket7Arka", DbType="NVarChar(MAX)")]
		public string Etiket7Arka
		{
			get
			{
				return this._Etiket7Arka;
			}
			set
			{
				if ((this._Etiket7Arka != value))
				{
					this.OnEtiket7ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket7Arka = value;
					this.SendPropertyChanged("Etiket7Arka");
					this.OnEtiket7ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket7ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket7ArkaEng
		{
			get
			{
				return this._Etiket7ArkaEng;
			}
			set
			{
				if ((this._Etiket7ArkaEng != value))
				{
					this.OnEtiket7ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket7ArkaEng = value;
					this.SendPropertyChanged("Etiket7ArkaEng");
					this.OnEtiket7ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket8Arka", DbType="NVarChar(MAX)")]
		public string Etiket8Arka
		{
			get
			{
				return this._Etiket8Arka;
			}
			set
			{
				if ((this._Etiket8Arka != value))
				{
					this.OnEtiket8ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket8Arka = value;
					this.SendPropertyChanged("Etiket8Arka");
					this.OnEtiket8ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket8ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket8ArkaEng
		{
			get
			{
				return this._Etiket8ArkaEng;
			}
			set
			{
				if ((this._Etiket8ArkaEng != value))
				{
					this.OnEtiket8ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket8ArkaEng = value;
					this.SendPropertyChanged("Etiket8ArkaEng");
					this.OnEtiket8ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket9Arka", DbType="NVarChar(MAX)")]
		public string Etiket9Arka
		{
			get
			{
				return this._Etiket9Arka;
			}
			set
			{
				if ((this._Etiket9Arka != value))
				{
					this.OnEtiket9ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket9Arka = value;
					this.SendPropertyChanged("Etiket9Arka");
					this.OnEtiket9ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket9ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket9ArkaEng
		{
			get
			{
				return this._Etiket9ArkaEng;
			}
			set
			{
				if ((this._Etiket9ArkaEng != value))
				{
					this.OnEtiket9ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket9ArkaEng = value;
					this.SendPropertyChanged("Etiket9ArkaEng");
					this.OnEtiket9ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket10Arka", DbType="NVarChar(MAX)")]
		public string Etiket10Arka
		{
			get
			{
				return this._Etiket10Arka;
			}
			set
			{
				if ((this._Etiket10Arka != value))
				{
					this.OnEtiket10ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket10Arka = value;
					this.SendPropertyChanged("Etiket10Arka");
					this.OnEtiket10ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket10ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket10ArkaEng
		{
			get
			{
				return this._Etiket10ArkaEng;
			}
			set
			{
				if ((this._Etiket10ArkaEng != value))
				{
					this.OnEtiket10ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket10ArkaEng = value;
					this.SendPropertyChanged("Etiket10ArkaEng");
					this.OnEtiket10ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket11Arka", DbType="NVarChar(MAX)")]
		public string Etiket11Arka
		{
			get
			{
				return this._Etiket11Arka;
			}
			set
			{
				if ((this._Etiket11Arka != value))
				{
					this.OnEtiket11ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket11Arka = value;
					this.SendPropertyChanged("Etiket11Arka");
					this.OnEtiket11ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket11ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket11ArkaEng
		{
			get
			{
				return this._Etiket11ArkaEng;
			}
			set
			{
				if ((this._Etiket11ArkaEng != value))
				{
					this.OnEtiket11ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket11ArkaEng = value;
					this.SendPropertyChanged("Etiket11ArkaEng");
					this.OnEtiket11ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket12Arka", DbType="NVarChar(MAX)")]
		public string Etiket12Arka
		{
			get
			{
				return this._Etiket12Arka;
			}
			set
			{
				if ((this._Etiket12Arka != value))
				{
					this.OnEtiket12ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket12Arka = value;
					this.SendPropertyChanged("Etiket12Arka");
					this.OnEtiket12ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket12ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket12ArkaEng
		{
			get
			{
				return this._Etiket12ArkaEng;
			}
			set
			{
				if ((this._Etiket12ArkaEng != value))
				{
					this.OnEtiket12ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket12ArkaEng = value;
					this.SendPropertyChanged("Etiket12ArkaEng");
					this.OnEtiket12ArkaEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket13Arka", DbType="NVarChar(MAX)")]
		public string Etiket13Arka
		{
			get
			{
				return this._Etiket13Arka;
			}
			set
			{
				if ((this._Etiket13Arka != value))
				{
					this.OnEtiket13ArkaChanging(value);
					this.SendPropertyChanging();
					this._Etiket13Arka = value;
					this.SendPropertyChanged("Etiket13Arka");
					this.OnEtiket13ArkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiket13ArkaEng", DbType="NVarChar(MAX)")]
		public string Etiket13ArkaEng
		{
			get
			{
				return this._Etiket13ArkaEng;
			}
			set
			{
				if ((this._Etiket13ArkaEng != value))
				{
					this.OnEtiket13ArkaEngChanging(value);
					this.SendPropertyChanging();
					this._Etiket13ArkaEng = value;
					this.SendPropertyChanged("Etiket13ArkaEng");
					this.OnEtiket13ArkaEngChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
